# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _graph_search_traced
else:
    import _graph_search_traced

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import faiss

def search_NSG_and_trace(index, n, x, k, labels, distances, visited_nodes):
    return _graph_search_traced.search_NSG_and_trace(index, n, x, k, labels, distances, visited_nodes)

def search_NSG_and_trace_untyped(index, n, x, k, labels, distances, visited_nodes):
    return _graph_search_traced.search_NSG_and_trace_untyped(index, n, x, k, labels, distances, visited_nodes)


import numpy as np
import faiss

def search_and_trace(self, x, k): 
    n, d = x.shape
    I = np.empty((n, k), dtype='int64')
    D = np.empty((n, k), dtype='float32')
    visited_nodes = faiss.Int64Vector()    
    search_NSG_and_trace_untyped(
        self, n, faiss.swig_ptr(x), k, 
        faiss.swig_ptr(I), faiss.swig_ptr(D), 
        visited_nodes)
    return D, I, faiss.vector_to_array(visited_nodes)

faiss.IndexNSG.search_and_trace = search_and_trace
